### ISSUE TITLE
Missing file assets/modules/docfinder/index.php in repo

### ISSUE THREAD

**Issue by q2apro** [extras-evolution/DocFinder#7]
From the readme: 

     include(MODX_BASE_PATH . 'assets/modules/docfinder/index.php');

However, there is no index.php file in the repository.

It should be: 

    include(MODX_BASE_PATH . 'assets/modules/docfinder/docfinder.module.php');

**Comment by Deesen** [comment]
Fixed with https://github.com/extras-evolution/DocFinder/commit/ddb8fdbb0db79e90a001d140dfbfedcfad7d6fee
